
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 21 14:16:17 CST 2019
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Multiplicacion = 4;
  public static final int Id = 10;
  public static final int Parentesis_c = 7;
  public static final int Division = 5;
  public static final int ERROR = 8;
  public static final int Parentesis_a = 6;
  public static final int EOF = 0;
  public static final int numero = 9;
  public static final int Suma = 2;
  public static final int error = 1;
  public static final int Numero_dec = 11;
  public static final int Resta = 3;
}

